# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
