# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20170725_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
