# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20170727_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.ManyToManyField(to='document.Level'),
        ),
    ]
