# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_document_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
