# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20170728_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
    ]
