# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 07:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20170728_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userratedocument',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
