# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20170728_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
