# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_document_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
