# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20170731_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='submit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
