# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edited_date',
            field=models.DateField(),
        ),
    ]
