# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0019_auto_20170806_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edited_date',
            field=models.DateField(default=datetime.datetime(2017, 8, 6, 14, 16, 5, 327806, tzinfo=utc)),
        ),
    ]
