# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0020_auto_20170806_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='edited_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
