# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_comment_is_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='number_of_likes',
        ),
        migrations.RemoveField(
            model_name='document',
            name='number_of_views',
        ),
    ]
