# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0025_auto_20170813_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='author',
        ),
    ]
