# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='biography',
            field=models.TextField(default=''),
        ),
    ]
