# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170724_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='avatar',
            field=models.ImageField(default='user_images/question_mark.jpg', upload_to='user_images'),
        ),
    ]
