# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170724_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='number_of_documents',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
    ]
